# Adapted from https://docs.github.com/actions/sharing-automations/creating-actions/creating-a-composite-action#creating-an-action-metadata-file
name: 'Hello World'
description: 'Greets someone'

inputs:
  who-to-greet:
    description: 'Who to greet'
    default: 'World'

outputs:
  rolled:
    description: 'A randomly generated number between 1 and 6 inclusive'
    value: ${{ steps.roll-die.outputs.roll }}

runs:
  using: 'composite'

  steps:

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Print greeting
      shell: pwsh
      env:
        INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}
      run: |
        $path = Join-Path $env:GITHUB_ACTION_PATH "greet.cs"
        if (-not (Test-Path $path)) {
          Write-Error "The greet.cs file does not exist at path: $path"
          exit 1
        }
        & $path $env:INPUT_WHO_TO_GREET

    - name: Roll a 6-sided die
      id: roll-die
      shell: pwsh
      run: |
        & (Join-Path $env:GITHUB_ACTION_PATH "roll-dice.cs")
