name: demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  csharp-action:
    runs-on: ubuntu-latest

    steps:

      - name: Use custom C# action
        uses: martincostello/custom-github-action-with-csharp@use-cs-files
        id: csharp
        with:
          who-to-greet: ${{ github.triggering_actor }}

      - name: Display dice roll
        env:
          ROLLED: ${{ steps.csharp.outputs.rolled }}
        shell: bash
        run: echo "You rolled $ROLLED"
